/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-01-17 12:46:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import jakarta.servlet.http.HttpSession;
import jakarta.servlet.http.HttpServletRequest;
import java.math.BigDecimal;
import java.math.RoundingMode;

public final class booking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Components/footer.jsp", Long.valueOf(1732558031730L));
    _jspx_dependants.put("/Components/navbar.jsp", Long.valueOf(1737009005227L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
    _jspx_imports_classes.add("java.math.BigDecimal");
    _jspx_imports_classes.add("jakarta.servlet.http.HttpServletRequest");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.math.RoundingMode");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Book Your Stay - HotelMate</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".booking-container {\r\n");
      out.write("	max-width: 1000px;\r\n");
      out.write("	margin: 40px auto;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	margin-top: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".booking-form {\r\n");
      out.write("	background: white;\r\n");
      out.write("	padding: 2rem;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".booking-summary {\r\n");
      out.write("	background: #f8f9fa;\r\n");
      out.write("	padding: 1.5rem;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	margin-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price-detail {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	margin-bottom: 0.5rem;\r\n");
      out.write("	padding: 0.5rem 0;\r\n");
      out.write("	border-bottom: 1px solid #dee2e6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price-detail:last-child {\r\n");
      out.write("	border-bottom: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-section {\r\n");
      out.write("	margin-bottom: 2rem;\r\n");
      out.write("	padding-bottom: 1rem;\r\n");
      out.write("	border-bottom: 1px solid #dee2e6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-section:last-child {\r\n");
      out.write("	border-bottom: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-title {\r\n");
      out.write("	color: #343a40;\r\n");
      out.write("	margin-bottom: 1.5rem;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-group-text {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-proceed {\r\n");
      out.write("	padding: 1rem 2rem;\r\n");
      out.write("	font-size: 1.1rem;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".room-type-select {\r\n");
      out.write("	margin-bottom: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".special-requests {\r\n");
      out.write("	min-height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error-feedback {\r\n");
      out.write("	color: #dc3545;\r\n");
      out.write("	font-size: 0.875rem;\r\n");
      out.write("	margin-top: 0.25rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".required-field::after {\r\n");
      out.write("	content: \"*\";\r\n");
      out.write("	color: #dc3545;\r\n");
      out.write("	margin-left: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel-preview {\r\n");
      out.write("	background: white;\r\n");
      out.write("	padding: 1.5rem;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel-image {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel-name {\r\n");
      out.write("	font-size: 1.5rem;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	color: #343a40;\r\n");
      out.write("	margin-bottom: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel-location {\r\n");
      out.write("	color: #6c757d;\r\n");
      out.write("	margin-bottom: 1rem;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	gap: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel-description {\r\n");
      out.write("	color: #495057;\r\n");
      out.write("	margin-bottom: 1rem;\r\n");
      out.write("	line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price-per-night {\r\n");
      out.write("	font-size: 1.25rem;\r\n");
      out.write("	color: #198754;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand d-flex align-items-center gap-2\"\r\n");
      out.write("			href=\"index.jsp\"> <img\r\n");
      out.write("			src=\"http://localhost:8080/HotelMate/Images/HotelmateLogo.png\"\r\n");
      out.write("			alt=\"HotelMate Logo\" width=\"60\" height=\"45\" class=\"d-inline-block\">\r\n");
      out.write("			<span class=\"brand-text\">HotelMate</span>\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<button class=\"navbar-toggler border-0\" type=\"button\"\r\n");
      out.write("			data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\"\r\n");
      out.write("			aria-controls=\"navbarNav\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("			<ul class=\"navbar-nav me-auto\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link \"\r\n");
      out.write("					aria-current=\"page\" href=\"index.jsp\">Home</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("					onclick=\"scrollToFeatures(event)\">Features</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"HotelDataServlet\">Hotels</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("					onclick=\"scrollToContact(event)\">Contact Us</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav ms-auto gap-2\">\r\n");
      out.write("				");

				if (session.getAttribute("userEmail") != null) {
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle user-profile\" href=\"#\"\r\n");
      out.write("					id=\"userDropdown\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("					aria-expanded=\"false\"> <i class=\"bi bi-person-circle\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"dropdown-menu dropdown-menu-end animate slideIn\"\r\n");
      out.write("						aria-labelledby=\"userDropdown\">\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"BookingDataServlet\">My\r\n");
      out.write("								Bookings</a></li>\r\n");
      out.write("						<li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("						<li><a class=\"dropdown-item text-danger\" href=\"LogoutServlet\">Logout</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link login-btn\"\r\n");
      out.write("					href=\"login.jsp\">Login</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link signup-btn\"\r\n");
      out.write("					href=\"signup.jsp\">Sign Up</a></li>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");

if (session.getAttribute("SessionSuccessMessage") != null) {

      out.write("\r\n");
      out.write("<div class=\"alert alert-success alert-dismissible fade show\"\r\n");
      out.write("	role=\"alert\">\r\n");
      out.write("	<i class=\"bi bi-check-circle-fill me-2\"></i>\r\n");
      out.write("	");
      out.print(session.getAttribute("SessionSuccessMessage"));
      out.write("\r\n");
      out.write("	<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"\r\n");
      out.write("		aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");

session.removeAttribute("SessionSuccessMessage");

      out.write('\r');
      out.write('\n');

}

      out.write("\r\n");
      out.write("\r\n");

if (session.getAttribute("SessionErrorMessage") != null) {

      out.write("\r\n");
      out.write("<div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("	<i class=\"bi bi-exclamation-triangle-fill me-2\"></i>\r\n");
      out.write("	");
      out.print(session.getAttribute("SessionErrorMessage"));
      out.write("\r\n");
      out.write("	<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"\r\n");
      out.write("		aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");

session.removeAttribute("SessionErrorMessage");

      out.write('\r');
      out.write('\n');

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".navbar {\r\n");
      out.write("	background-color: #343a40;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	padding: 0.75rem 1.5rem;\r\n");
      out.write("	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	z-index: 1000;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	margin: 5px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	font-size: 1.4rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".brand-text {\r\n");
      out.write("	background: linear-gradient(45deg, #97CC04, #85B403);\r\n");
      out.write("	-webkit-background-clip: text;\r\n");
      out.write("	-webkit-text-fill-color: transparent;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding: 0.5rem 1rem;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link::after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 0;\r\n");
      out.write("	height: 2px;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	background-color: #97CC04;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	transform: translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link:hover::after {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn, .signup-btn {\r\n");
      out.write("	background-color: #97CC04;\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	padding: 0.5rem 1.25rem !important;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	border: 2px solid transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn:hover, .signup-btn:hover {\r\n");
      out.write("	background-color: #85B403;\r\n");
      out.write("	transform: translateY(-1px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn {\r\n");
      out.write("	background-color: transparent;\r\n");
      out.write("	border: 2px solid #97CC04;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn:hover {\r\n");
      out.write("	background-color: #97CC04;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-profile i {\r\n");
      out.write("	font-size: 1.75rem;\r\n");
      out.write("	color: #97CC04;\r\n");
      out.write("	transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-profile:hover i {\r\n");
      out.write("	color: #85B403;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("	border: none;\r\n");
      out.write("	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	padding: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-item {\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("	padding: 0.5rem 1rem;\r\n");
      out.write("	transition: all 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-item:hover {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("	transform: translateX(5px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".alert {\r\n");
      out.write("	margin-top: 90px;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	padding: 1rem;\r\n");
      out.write("	animation: slideInDown 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes slideInDown {from { transform:translateY(-100%);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("	transform: translateY(0);\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Dropdown animation */\r\n");
      out.write(".animate {\r\n");
      out.write("	animation-duration: 0.3s;\r\n");
      out.write("	-webkit-animation-duration: 0.3s;\r\n");
      out.write("	animation-fill-mode: both;\r\n");
      out.write("	-webkit-animation-fill-mode: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes slideIn { 0% {\r\n");
      out.write("	transform: translateY(1rem);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("100\r\n");
      out.write("%\r\n");
      out.write("{\r\n");
      out.write("transform\r\n");
      out.write(":\r\n");
      out.write("translateY(\r\n");
      out.write("0rem\r\n");
      out.write(");\r\n");
      out.write("opacity\r\n");
      out.write(":\r\n");
      out.write("1;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write(".slideIn {\r\n");
      out.write("	-webkit-animation-name: slideIn;\r\n");
      out.write("	animation-name: slideIn;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 991.98px) {\r\n");
      out.write("	.navbar-collapse {\r\n");
      out.write("		background-color: #343a40;\r\n");
      out.write("		padding: 1rem;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		margin-top: 1rem;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-link::after {\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("	.login-btn, .signup-btn {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		margin: 0.5rem 0;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function scrollToFeatures(event) {\r\n");
      out.write("		event.preventDefault();\r\n");
      out.write("		localStorage.setItem('scrollToFeatures', 'true');\r\n");
      out.write("		window.location.href = \"index.jsp\";\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function scrollToContact(event) {\r\n");
      out.write("		event.preventDefault();\r\n");
      out.write("		localStorage.setItem('scrollToContact', 'true');\r\n");
      out.write("		window.location.href = \"index.jsp\";\r\n");
      out.write("	}\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container booking-container\">\r\n");
      out.write("\r\n");
      out.write("		<h2 class=\"text-center mb-4\">Complete Your Booking</h2>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"hotel-preview\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<img src=\"");
      out.print(request.getAttribute("imageUrl"));
      out.write("\"\r\n");
      out.write("						alt=\"");
      out.print(request.getAttribute("name"));
      out.write("\" class=\"hotel-image\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-8\">\r\n");
      out.write("					<h2 class=\"hotel-name\">");
      out.print(request.getAttribute("name"));
      out.write("</h2>\r\n");
      out.write("					<div class=\"hotel-location\">\r\n");
      out.write("						<i class=\"bi bi-geo-alt-fill\"></i> <span>");
      out.print(request.getAttribute("location"));
      out.write(",\r\n");
      out.write("							");
      out.print(request.getAttribute("city"));
      out.write(',');
      out.write(' ');
      out.print(request.getAttribute("state"));
      out.write(",\r\n");
      out.write("							");
      out.print(request.getAttribute("country"));
      out.write("</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"hotel-description\">");
      out.print(request.getAttribute("description"));
      out.write("</p>\r\n");
      out.write("					<p class=\"price-per-night\">\r\n");
      out.write("						<i class=\"bi bi-tag-fill me-2\"></i>₹");
      out.print(request.getAttribute("pricePerNight"));
      out.write("\r\n");
      out.write("						per night\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-8\">\r\n");
      out.write("				<form class=\"booking-form\" id=\"bookingForm\"\r\n");
      out.write("					action=\"ProcessPaymentServlet\" method=\"POST\">\r\n");
      out.write("					<div class=\"form-section\">\r\n");
      out.write("						<h4 class=\"section-title\">Room Selection</h4>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-6 mb-3\">\r\n");
      out.write("								<label class=\"form-label required-field\">Check-in Date</label> <input\r\n");
      out.write("									type=\"date\" class=\"form-control\" id=\"checkIn\" name=\"checkIn\"\r\n");
      out.write("									required>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 mb-3\">\r\n");
      out.write("								<label class=\"form-label required-field\">Check-out Date</label>\r\n");
      out.write("								<input type=\"date\" class=\"form-control\" id=\"checkOut\"\r\n");
      out.write("									name=\"checkOut\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-6 mb-3\">\r\n");
      out.write("								<label class=\"form-label required-field\">Adults</label> <select\r\n");
      out.write("									class=\"form-select\" id=\"adults\" name=\"adults\" required>\r\n");
      out.write("									<option value=\"1\">1</option>\r\n");
      out.write("									<option value=\"2\">2</option>\r\n");
      out.write("									<option value=\"3\">3</option>\r\n");
      out.write("									<option value=\"4\">4</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 mb-3\">\r\n");
      out.write("								<label class=\"form-label\">Children</label> <select\r\n");
      out.write("									class=\"form-select\" id=\"children\" name=\"children\">\r\n");
      out.write("									<option value=\"0\">0</option>\r\n");
      out.write("									<option value=\"1\">1</option>\r\n");
      out.write("									<option value=\"2\">2</option>\r\n");
      out.write("									<option value=\"3\">3</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"form-section\">\r\n");
      out.write("						<h4 class=\"section-title\">Guest Information</h4>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-6 mb-3\">\r\n");
      out.write("								<label class=\"form-label required-field\">First Name</label> <input\r\n");
      out.write("									type=\"text\" class=\"form-control\" name=\"firstName\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 mb-3\">\r\n");
      out.write("								<label class=\"form-label required-field\">Last Name</label> <input\r\n");
      out.write("									type=\"text\" class=\"form-control\" name=\"lastName\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label class=\"form-label required-field\">Email Address</label> <input\r\n");
      out.write("								type=\"email\" class=\"form-control\" name=\"email\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label class=\"form-label required-field\">Phone Number</label> <input\r\n");
      out.write("								type=\"tel\" class=\"form-control\" name=\"phone\"\r\n");
      out.write("								placeholder=\"+91 Phone Number\" aria-label=\"Phone Number\"\r\n");
      out.write("								aria-describedby=\"phone-addon\" pattern=\"^\\+91[6-9][0-9]{9}$\"\r\n");
      out.write("								title=\"Enter a valid Indian phone number starting with +91 and followed by 10 digits starting with 6, 7, 8, or 9.\"\r\n");
      out.write("								required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label class=\"form-label\">Special Requests</label>\r\n");
      out.write("							<textarea class=\"form-control special-requests\"\r\n");
      out.write("								name=\"specialRequests\"\r\n");
      out.write("								placeholder=\"Any special requests or preferences...\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"form-section\">\r\n");
      out.write("						<h4 class=\"section-title\">Additional Services</h4>\r\n");
      out.write("						<div class=\"form-check mb-2\">\r\n");
      out.write("							<input class=\"form-check-input\" type=\"checkbox\" id=\"breakfast\"\r\n");
      out.write("								data-price=\"500\"> <label class=\"form-check-label\"\r\n");
      out.write("								for=\"breakfast\">Breakfast (₹500 per person per day)</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-check mb-2\">\r\n");
      out.write("							<input class=\"form-check-input\" type=\"checkbox\" id=\"airport\"\r\n");
      out.write("								data-price=\"1000\"> <label class=\"form-check-label\"\r\n");
      out.write("								for=\"airport\">Airport Transfer (₹1000)</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-check mb-2\">\r\n");
      out.write("							<input class=\"form-check-input\" type=\"checkbox\" id=\"earlyCheckin\"\r\n");
      out.write("								data-price=\"1500\"> <label class=\"form-check-label\"\r\n");
      out.write("								for=\"earlyCheckin\">Early Check-in (₹1500 if available)</label>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"hidden\" name=\"hotelId\"\r\n");
      out.write("						value=\"");
      out.print(request.getAttribute("hotelId"));
      out.write("\"> <input\r\n");
      out.write("						type=\"hidden\" name=\"totalAmount\" id=\"hiddenTotalAmount\"> <input\r\n");
      out.write("						type=\"hidden\" name=\"hasBreakfast\" id=\"hiddenBreakfast\"\r\n");
      out.write("						value=\"false\"> <input type=\"hidden\"\r\n");
      out.write("						name=\"hasAirportTransfer\" id=\"hiddenAirportTransfer\" value=\"false\">\r\n");
      out.write("					<input type=\"hidden\" name=\"hasEarlyCheckin\" id=\"hiddenEarlyCheckin\"\r\n");
      out.write("						value=\"false\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-lg-4\">\r\n");
      out.write("				<div class=\"booking-form\">\r\n");
      out.write("					<h4 class=\"section-title\">Booking Summary</h4>\r\n");
      out.write("					<div class=\"booking-summary\">\r\n");
      out.write("						<div class=\"price-detail\">\r\n");
      out.write("							<span>Room Charges</span> <span id=\"roomCharges\">₹0</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"price-detail\">\r\n");
      out.write("							<span>Taxes & Fees (18%)</span> <span id=\"taxes\">₹0</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"price-detail\">\r\n");
      out.write("							<span>Additional Services</span> <span id=\"additionalServices\">₹0</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"price-detail\">\r\n");
      out.write("							<span>Total Amount</span> <span id=\"totalAmount\">₹0</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button type=\"submit\" form=\"bookingForm\"\r\n");
      out.write("						class=\"btn btn-primary w-100 btn-proceed\">\r\n");
      out.write("						<i class=\"bi bi-lock-fill me-2\"></i>Proceed to Payment\r\n");
      out.write("					</button>\r\n");
      out.write("					<p class=\"text-muted small text-center mt-3\">\r\n");
      out.write("						<i class=\"bi bi-shield-check me-1\"></i> Your payment information\r\n");
      out.write("						is secure and encrypted\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	");

	BigDecimal pricePerNight = (BigDecimal) request.getAttribute("pricePerNight");
	DecimalFormat df = new DecimalFormat("#0.00");
	String formattedPrice = df.format(pricePerNight);
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	const today = new Date().toISOString().split('T')[0];\r\n");
      out.write("    document.getElementById(\"checkIn\").value = today;\r\n");
      out.write("    document.getElementById(\"checkOut\").value = today;\r\n");
      out.write("    document.getElementById('checkIn').setAttribute('min', today);\r\n");
      out.write("    document.getElementById('checkOut').setAttribute('min', today);\r\n");
      out.write("	const pricePerNight = ");
      out.print(formattedPrice);
      out.write(";\r\n");
      out.write("\r\n");
      out.write("	function formatCurrency(amount) {\r\n");
      out.write("	    return \"₹\" + amount;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function calculateTotal() {\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	    \r\n");
      out.write("	    const checkInDate = new Date(document.getElementById(\"checkIn\").value);\r\n");
      out.write("	    const checkOutDate = new Date(document.getElementById(\"checkOut\").value);\r\n");
      out.write("	    \r\n");
      out.write("	    if (checkInDate >= checkOutDate) {\r\n");
      out.write("	        return; \r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    const nights = Math.ceil((checkOutDate - checkInDate) / (1000 * 60 * 60 * 24));\r\n");
      out.write("	    \r\n");
      out.write("	    const roomCharges = nights * pricePerNight;\r\n");
      out.write("	    \r\n");
      out.write("	    const taxes = roomCharges * 0.18;\r\n");
      out.write("	    \r\n");
      out.write("	    const services = Array.from(document.querySelectorAll('.form-check-input:checked'));\r\n");
      out.write("	    let serviceCost = services.reduce((total, service) => {\r\n");
      out.write("	        return total + parseFloat(service.dataset.price || 0);\r\n");
      out.write("	    }, 0);\r\n");
      out.write("	    \r\n");
      out.write("	    if (document.getElementById(\"breakfast\").checked) {\r\n");
      out.write("	        const adults = parseInt(document.getElementById(\"adults\").value) || 0;\r\n");
      out.write("	        const children = parseInt(document.getElementById(\"children\").value) || 0;\r\n");
      out.write("	        const totalGuests = adults + children;\r\n");
      out.write("	        serviceCost += (500 * totalGuests * nights) - 500; \r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    const total = roomCharges + taxes + serviceCost;\r\n");
      out.write("	    \r\n");
      out.write("	    document.getElementById(\"roomCharges\").textContent = formatCurrency(roomCharges);\r\n");
      out.write("	    document.getElementById(\"taxes\").textContent = formatCurrency(taxes);\r\n");
      out.write("	    document.getElementById(\"additionalServices\").textContent = formatCurrency(serviceCost);\r\n");
      out.write("	    document.getElementById(\"totalAmount\").textContent = formatCurrency(total);\r\n");
      out.write("	    document.getElementById(\"hiddenTotalAmount\").value = total;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function setupEventListeners() {\r\n");
      out.write("	    document.getElementById(\"checkIn\").addEventListener(\"change\", calculateTotal);\r\n");
      out.write("	    document.getElementById(\"checkOut\").addEventListener(\"change\", calculateTotal);\r\n");
      out.write("	    \r\n");
      out.write("	    document.getElementById(\"adults\").addEventListener(\"change\", calculateTotal);\r\n");
      out.write("	    document.getElementById(\"children\").addEventListener(\"change\", calculateTotal);\r\n");
      out.write("	    \r\n");
      out.write("	    const services = document.querySelectorAll('.form-check-input');\r\n");
      out.write("	    services.forEach(service => {\r\n");
      out.write("	        service.addEventListener(\"change\", calculateTotal);\r\n");
      out.write("	    });\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	document.addEventListener(\"DOMContentLoaded\", () => {\r\n");
      out.write("	    setupEventListeners();\r\n");
      out.write("	    document.getElementById(\"roomCharges\").textContent = formatCurrency(0);\r\n");
      out.write("	    document.getElementById(\"taxes\").textContent = formatCurrency(0);\r\n");
      out.write("	    document.getElementById(\"additionalServices\").textContent = formatCurrency(0);\r\n");
      out.write("	    document.getElementById(\"totalAmount\").textContent = formatCurrency(0);\r\n");
      out.write("	    document.getElementById(\"hiddenTotalAmount\").value = total;\r\n");
      out.write("	    document.getElementById(\"hiddenBreakfast\").value = document.getElementById(\"breakfast\").checked;\r\n");
      out.write("	    document.getElementById(\"hiddenAirportTransfer\").value = document.getElementById(\"airport\").checked;\r\n");
      out.write("	    document.getElementById(\"hiddenEarlyCheckin\").value = document.getElementById(\"earlyCheckin\").checked;\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("	<script src=\"https://checkout.razorpay.com/v1/checkout.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("document.getElementById('bookingForm').addEventListener('submit', function(e) {\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("    console.log('Form submission started');\r\n");
      out.write("\r\n");
      out.write("    const formData = new FormData(this);\r\n");
      out.write("    const urlEncodedData = new URLSearchParams(formData).toString();\r\n");
      out.write("    console.log('Initial form data:', Object.fromEntries(formData));\r\n");
      out.write("\r\n");
      out.write("    fetch('ProcessPaymentServlet', {\r\n");
      out.write("        method: 'POST',\r\n");
      out.write("        headers: {\r\n");
      out.write("            'Content-Type': 'application/x-www-form-urlencoded'\r\n");
      out.write("        },\r\n");
      out.write("        body: urlEncodedData\r\n");
      out.write("    })\r\n");
      out.write("    .then(response => {\r\n");
      out.write("        console.log('ProcessPaymentServlet response status:', response.status);\r\n");
      out.write("        if (!response.ok) {\r\n");
      out.write("            throw new Error('Network response was not ok: ' + response.status);\r\n");
      out.write("        }\r\n");
      out.write("        return response.json();\r\n");
      out.write("    })\r\n");
      out.write("    .then(data => {\r\n");
      out.write("        console.log('Payment initialization data:', data);\r\n");
      out.write("        \r\n");
      out.write("        const options = {\r\n");
      out.write("            key: data.keyId,\r\n");
      out.write("            amount: data.amount,\r\n");
      out.write("            currency: data.currency,\r\n");
      out.write("            name: \"HotelMate\",\r\n");
      out.write("            description: \"Hotel Booking Payment\",\r\n");
      out.write("            order_id: data.orderId,\r\n");
      out.write("            handler: function (response) {\r\n");
      out.write("                console.log('Razorpay payment successful:', response);\r\n");
      out.write("                \r\n");
      out.write("                const bookingData = new FormData(document.getElementById('bookingForm'));\r\n");
      out.write("                bookingData.append('paymentId', response.razorpay_payment_id);\r\n");
      out.write("                bookingData.append('orderId', data.orderId);\r\n");
      out.write("                \r\n");
      out.write("                console.log('Sending booking data:', Object.fromEntries(bookingData));\r\n");
      out.write("\r\n");
      out.write("                const bookingUrlEncoded = new URLSearchParams(bookingData).toString();\r\n");
      out.write("                \r\n");
      out.write("                fetch('BookingServlet', {\r\n");
      out.write("                    method: 'POST',\r\n");
      out.write("                    headers: {\r\n");
      out.write("                        'Content-Type': 'application/x-www-form-urlencoded'\r\n");
      out.write("                    },\r\n");
      out.write("                    body: bookingUrlEncoded\r\n");
      out.write("                })\r\n");
      out.write("                .then(response => {\r\n");
      out.write("                    console.log('BookingServlet response status:', response.status);\r\n");
      out.write("                    if (!response.ok) {\r\n");
      out.write("                        throw new Error('Error saving booking: ' + response.status);\r\n");
      out.write("                    }\r\n");
      out.write("                    return response.text();\r\n");
      out.write("                })\r\n");
      out.write("                .then(bookingResponse => {\r\n");
      out.write("                    console.log('Booking success response:', bookingResponse);\r\n");
      out.write("                    window.location.href = 'BookingDataServlet';\r\n");
      out.write("                    \r\n");
      out.write("                })\r\n");
      out.write("                .catch(error => {\r\n");
      out.write("                    console.error('Booking error:', error);\r\n");
      out.write("                    alert('Payment was successful but there was an error saving your booking. Please contact support.\\nError: ' + error.message);\r\n");
      out.write("                });\r\n");
      out.write("            },\r\n");
      out.write("            prefill: {\r\n");
      out.write("                name: document.querySelector('[name=\"firstName\"]').value + ' ' + \r\n");
      out.write("                     document.querySelector('[name=\"lastName\"]').value,\r\n");
      out.write("                email: document.querySelector('[name=\"email\"]').value,\r\n");
      out.write("                contact: document.querySelector('[name=\"phone\"]').value\r\n");
      out.write("            },\r\n");
      out.write("            theme: {\r\n");
      out.write("                color: \"#3399cc\"\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        console.log('Initializing Razorpay with options:', {...options, handler: '[Function]'});\r\n");
      out.write("        \r\n");
      out.write("        const rzp = new Razorpay(options);\r\n");
      out.write("        rzp.on('payment.failed', function (response){\r\n");
      out.write("            console.error('Payment failed:', response);\r\n");
      out.write("            alert('Payment failed: ' + response.error.description);\r\n");
      out.write("        });\r\n");
      out.write("        rzp.open();\r\n");
      out.write("    })\r\n");
      out.write("    .catch(error => {\r\n");
      out.write("        console.error('Payment initialization error:', error);\r\n");
      out.write("        alert('An error occurred while processing payment: ' + error.message);\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("document.addEventListener('payment.failed', function(response) {\r\n");
      out.write("    console.error('Payment failed event:', response);\r\n");
      out.write("    alert('Payment failed. Please try again.');\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("<style>\r\n");
      out.write(".footer {\r\n");
      out.write("	padding: 20px 0;\r\n");
      out.write("	background-color: #f1f1f1;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class='footer' id=\"footer\">\r\n");
      out.write("	<p class=\"text-center text-secondary\">© HotelMate 2024 - All\r\n");
      out.write("		rights reserved</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
