/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-01-17 18:49:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import jakarta.servlet.http.HttpSession;
import jakarta.servlet.http.HttpServletRequest;

public final class details_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Components/footer.jsp", Long.valueOf(1737130216921L));
    _jspx_dependants.put("/Components/navbar.jsp", Long.valueOf(1737009005227L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
    _jspx_imports_classes.add("jakarta.servlet.http.HttpServletRequest");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Hotel - HotelMate</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(":root {\r\n");
      out.write("	--primary-dark: #343a40;\r\n");
      out.write("	--primary-green: #198754;\r\n");
      out.write("	--secondary-green: #507555;\r\n");
      out.write("	--light-green: #e8f5e9;\r\n");
      out.write("	--accent-green: #75a17c;\r\n");
      out.write("	--hover-green: #1a4121;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel-details-container {\r\n");
      out.write("	margin-top: 115px;\r\n");
      out.write("	margin-bottom: 4rem;\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	border-radius: 1rem;\r\n");
      out.write("	box-shadow: 0 0.5rem 1rem rgba(44, 85, 48, 0.08);\r\n");
      out.write("	padding: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel-title {\r\n");
      out.write("	color: var(--primary-dark);\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	font-size: 2.5rem;\r\n");
      out.write("	margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel-description {\r\n");
      out.write("	color: #495057;\r\n");
      out.write("	font-size: 1.1rem;\r\n");
      out.write("	line-height: 1.6;\r\n");
      out.write("	margin-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel {\r\n");
      out.write("	border-radius: 1rem;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	box-shadow: 0 0.5rem 1rem rgba(44, 85, 48, 0.1);\r\n");
      out.write("	margin-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-item img {\r\n");
      out.write("	height: 600px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price {\r\n");
      out.write("	font-size: 2rem;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	color: var(--primary-green);\r\n");
      out.write("	margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rating {\r\n");
      out.write("	font-size: 1.25rem;\r\n");
      out.write("	color: #ffc1;\r\n");
      out.write("	margin-bottom: 1.5rem;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	gap: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rating i {\r\n");
      out.write("	color: #ffc1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".amenities-list {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	gap: 0.75rem;\r\n");
      out.write("	margin-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".amenities-items {\r\n");
      out.write("	background-color: var(--light-green);\r\n");
      out.write("	color: var(--primary-green);\r\n");
      out.write("	padding: 0.5rem 1rem;\r\n");
      out.write("	border-radius: 9999px;\r\n");
      out.write("	font-size: 0.875rem;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	transition: all 0.2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".amenities-items:hover {\r\n");
      out.write("	background-color: var(--accent-green);\r\n");
      out.write("	color: white;\r\n");
      out.write("	transform: translateY(-1px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-info {\r\n");
      out.write("	background-color: var(--light-green);\r\n");
      out.write("	padding: 1.5rem;\r\n");
      out.write("	border-radius: 0.75rem;\r\n");
      out.write("	margin-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-info i {\r\n");
      out.write("	color: var(--primary-green);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".book-button {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 1rem;\r\n");
      out.write("	font-size: 1.125rem;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	transition: all 0.2s;\r\n");
      out.write("	background-color: var(--primary-green) !important;\r\n");
      out.write("	border-color: var(--primary-green) !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".book-button:hover {\r\n");
      out.write("	background-color: var(--hover-green) !important;\r\n");
      out.write("	transform: translateY(-2px);\r\n");
      out.write("	box-shadow: 0 0.5rem 1rem rgba(44, 85, 48, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back-button {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 0.75rem;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	color: var(--primary-green);\r\n");
      out.write("	border-color: var(--primary-green);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back-button:hover {\r\n");
      out.write("	background-color: var(--primary-green);\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".location-info {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	gap: 0.5rem;\r\n");
      out.write("	color: var(--primary-dark);\r\n");
      out.write("	margin-bottom: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".location-info i {\r\n");
      out.write("	color: var(--primary-green);\r\n");
      out.write("	font-size: 1.25rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-title {\r\n");
      out.write("	color: var(--primary-dark);\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	margin-bottom: 1rem;\r\n");
      out.write("	padding-bottom: 0.5rem;\r\n");
      out.write("	border-bottom: 2px solid var(--light-green);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".booking-card {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border: 1px solid var(--light-green);\r\n");
      out.write("	border-radius: 1rem;\r\n");
      out.write("	padding: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price-label {\r\n");
      out.write("	color: var(--secondary-green);\r\n");
      out.write("	font-size: 0.875rem;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand d-flex align-items-center gap-2\"\r\n");
      out.write("			href=\"index.jsp\"> <img\r\n");
      out.write("			src=\"http://localhost:8080/HotelMate/Images/HotelmateLogo.png\"\r\n");
      out.write("			alt=\"HotelMate Logo\" width=\"60\" height=\"45\" class=\"d-inline-block\">\r\n");
      out.write("			<span class=\"brand-text\">HotelMate</span>\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<button class=\"navbar-toggler border-0\" type=\"button\"\r\n");
      out.write("			data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\"\r\n");
      out.write("			aria-controls=\"navbarNav\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("			<ul class=\"navbar-nav me-auto\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link \"\r\n");
      out.write("					aria-current=\"page\" href=\"index.jsp\">Home</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("					onclick=\"scrollToFeatures(event)\">Features</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"HotelDataServlet\">Hotels</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("					onclick=\"scrollToContact(event)\">Contact Us</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav ms-auto gap-2\">\r\n");
      out.write("				");

				if (session.getAttribute("userEmail") != null) {
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle user-profile\" href=\"#\"\r\n");
      out.write("					id=\"userDropdown\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("					aria-expanded=\"false\"> <i class=\"bi bi-person-circle\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"dropdown-menu dropdown-menu-end animate slideIn\"\r\n");
      out.write("						aria-labelledby=\"userDropdown\">\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"BookingDataServlet\">My\r\n");
      out.write("								Bookings</a></li>\r\n");
      out.write("						<li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("						<li><a class=\"dropdown-item text-danger\" href=\"LogoutServlet\">Logout</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link login-btn\"\r\n");
      out.write("					href=\"login.jsp\">Login</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link signup-btn\"\r\n");
      out.write("					href=\"signup.jsp\">Sign Up</a></li>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");

if (session.getAttribute("SessionSuccessMessage") != null) {

      out.write("\r\n");
      out.write("<div class=\"alert alert-success alert-dismissible fade show\"\r\n");
      out.write("	role=\"alert\">\r\n");
      out.write("	<i class=\"bi bi-check-circle-fill me-2\"></i>\r\n");
      out.write("	");
      out.print(session.getAttribute("SessionSuccessMessage"));
      out.write("\r\n");
      out.write("	<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"\r\n");
      out.write("		aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");

session.removeAttribute("SessionSuccessMessage");

      out.write('\r');
      out.write('\n');

}

      out.write("\r\n");
      out.write("\r\n");

if (session.getAttribute("SessionErrorMessage") != null) {

      out.write("\r\n");
      out.write("<div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("	<i class=\"bi bi-exclamation-triangle-fill me-2\"></i>\r\n");
      out.write("	");
      out.print(session.getAttribute("SessionErrorMessage"));
      out.write("\r\n");
      out.write("	<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"\r\n");
      out.write("		aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");

session.removeAttribute("SessionErrorMessage");

      out.write('\r');
      out.write('\n');

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".navbar {\r\n");
      out.write("	background-color: #343a40;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	padding: 0.75rem 1.5rem;\r\n");
      out.write("	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	z-index: 1000;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	margin: 5px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	font-size: 1.4rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".brand-text {\r\n");
      out.write("	background: linear-gradient(45deg, #97CC04, #85B403);\r\n");
      out.write("	-webkit-background-clip: text;\r\n");
      out.write("	-webkit-text-fill-color: transparent;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding: 0.5rem 1rem;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link::after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 0;\r\n");
      out.write("	height: 2px;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	background-color: #97CC04;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	transform: translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link:hover::after {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn, .signup-btn {\r\n");
      out.write("	background-color: #97CC04;\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	padding: 0.5rem 1.25rem !important;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	border: 2px solid transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn:hover, .signup-btn:hover {\r\n");
      out.write("	background-color: #85B403;\r\n");
      out.write("	transform: translateY(-1px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn {\r\n");
      out.write("	background-color: transparent;\r\n");
      out.write("	border: 2px solid #97CC04;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn:hover {\r\n");
      out.write("	background-color: #97CC04;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-profile i {\r\n");
      out.write("	font-size: 1.75rem;\r\n");
      out.write("	color: #97CC04;\r\n");
      out.write("	transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-profile:hover i {\r\n");
      out.write("	color: #85B403;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("	border: none;\r\n");
      out.write("	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	padding: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-item {\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("	padding: 0.5rem 1rem;\r\n");
      out.write("	transition: all 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-item:hover {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("	transform: translateX(5px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".alert {\r\n");
      out.write("	margin-top: 90px;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	padding: 1rem;\r\n");
      out.write("	animation: slideInDown 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes slideInDown {from { transform:translateY(-100%);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("	transform: translateY(0);\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Dropdown animation */\r\n");
      out.write(".animate {\r\n");
      out.write("	animation-duration: 0.3s;\r\n");
      out.write("	-webkit-animation-duration: 0.3s;\r\n");
      out.write("	animation-fill-mode: both;\r\n");
      out.write("	-webkit-animation-fill-mode: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes slideIn { 0% {\r\n");
      out.write("	transform: translateY(1rem);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("100\r\n");
      out.write("%\r\n");
      out.write("{\r\n");
      out.write("transform\r\n");
      out.write(":\r\n");
      out.write("translateY(\r\n");
      out.write("0rem\r\n");
      out.write(");\r\n");
      out.write("opacity\r\n");
      out.write(":\r\n");
      out.write("1;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write(".slideIn {\r\n");
      out.write("	-webkit-animation-name: slideIn;\r\n");
      out.write("	animation-name: slideIn;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 991.98px) {\r\n");
      out.write("	.navbar-collapse {\r\n");
      out.write("		background-color: #343a40;\r\n");
      out.write("		padding: 1rem;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		margin-top: 1rem;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-link::after {\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("	.login-btn, .signup-btn {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		margin: 0.5rem 0;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function scrollToFeatures(event) {\r\n");
      out.write("		event.preventDefault();\r\n");
      out.write("		localStorage.setItem('scrollToFeatures', 'true');\r\n");
      out.write("		window.location.href = \"index.jsp\";\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function scrollToContact(event) {\r\n");
      out.write("		event.preventDefault();\r\n");
      out.write("		localStorage.setItem('scrollToContact', 'true');\r\n");
      out.write("		window.location.href = \"index.jsp\";\r\n");
      out.write("	}\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	// Retrieve hotel data from request attribute
	Map<String, Object> hotelDetails = (Map<String, Object>) request.getAttribute("hotelDetails");

	// Extract values from the hotelDetails map
	String name = (String) hotelDetails.get("name");
	String description = (String) hotelDetails.get("description");
	String location = (String) hotelDetails.get("location");
	String city = (String) hotelDetails.get("city");
	String state = (String) hotelDetails.get("state");
	String country = (String) hotelDetails.get("country");
	String zipCode = (String) hotelDetails.get("zipCode");
	double pricePerNight = (double) hotelDetails.get("pricePerNight");
	float rating = (float) hotelDetails.get("rating");
	String amenities = (String) hotelDetails.get("amenities");
	String contactEmail = (String) hotelDetails.get("contactEmail");
	String contactPhone = (String) hotelDetails.get("contactPhone");
	String images = (String) hotelDetails.get("imageUrl");
	String[] imageUrls = images.split(",");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container hotel-details-container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-8\">\r\n");
      out.write("				<h1 class=\"hotel-title\">");
      out.print(name);
      out.write("</h1>\r\n");
      out.write("				<p class=\"hotel-description\">");
      out.print(description);
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("				<!-- Carousel -->\r\n");
      out.write("				<div id=\"hotelCarousel\" class=\"carousel slide\"\r\n");
      out.write("					data-bs-ride=\"carousel\">\r\n");
      out.write("					<div class=\"carousel-inner\">\r\n");
      out.write("						");

						for (int i = 0; i < imageUrls.length; i++) {
						
      out.write("\r\n");
      out.write("						<div class=\"carousel-item ");
      out.print((i == 0) ? "active" : "");
      out.write("\">\r\n");
      out.write("							<img src=\"");
      out.print(imageUrls[i].trim());
      out.write("\" class=\"d-block w-100\"\r\n");
      out.write("								alt=\"Hotel Image\">\r\n");
      out.write("						</div>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					");

					if (imageUrls.length > 1) {
					
      out.write("\r\n");
      out.write("					<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("						data-bs-target=\"#hotelCarousel\" data-bs-slide=\"prev\">\r\n");
      out.write("						<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("						<span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("						data-bs-target=\"#hotelCarousel\" data-bs-slide=\"next\">\r\n");
      out.write("						<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("						<span class=\"visually-hidden\">Next</span>\r\n");
      out.write("					</button>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Amenities -->\r\n");
      out.write("				<h3 class=\"section-title\">Amenities</h3>\r\n");
      out.write("				<div class=\"amenities-list\">\r\n");
      out.write("					");

					String[] amenitiesList = amenities.split(",");
					for (String amenity : amenitiesList) {
						amenity = amenity.trim();
					
      out.write("\r\n");
      out.write("					<span class=\"amenities-items\"> ");
      out.print(amenity);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Location -->\r\n");
      out.write("				<div class=\"location-info\">\r\n");
      out.write("					<i class=\"bi bi-geo-alt-fill\"></i> <span> ");
      out.print(location);
      out.write(',');
      out.write(' ');
      out.print(city);
      out.write(",\r\n");
      out.write("						");
      out.print(state);
      out.write(',');
      out.write(' ');
      out.print(country);
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(zipCode);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Contact Information -->\r\n");
      out.write("				<div class=\"contact-info\">\r\n");
      out.write("					<h4 class=\"section-title\">Contact Information</h4>\r\n");
      out.write("					<div class=\"d-flex align-items-center mb-3\">\r\n");
      out.write("						<i class=\"bi bi-envelope-fill me-2\"></i> <span><strong>Email:</strong>\r\n");
      out.write("							");
      out.print(contactEmail);
      out.write("</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"d-flex align-items-center\">\r\n");
      out.write("						<i class=\"bi bi-telephone-fill me-2\"></i> <span><strong>Phone:</strong>\r\n");
      out.write("							");
      out.print(contactPhone);
      out.write("</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Booking Section -->\r\n");
      out.write("			<div class=\"col-lg-4\">\r\n");
      out.write("				<div class=\"position-sticky\" style=\"top: 2rem;\">\r\n");
      out.write("					<div class=\"booking-card shadow-sm\">\r\n");
      out.write("						<div class=\"rating\">\r\n");
      out.write("							<i class=\"bi bi-star-fill\"></i> <span>");
      out.print(rating);
      out.write(" / 5.0</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"price\">\r\n");
      out.write("							₹");
      out.print(String.format("%,.0f", pricePerNight));
      out.write("</div>\r\n");
      out.write("						<p class=\"price-label mb-4\">per night</p>\r\n");
      out.write("						<a href=\"HotelBookingServlet?hotelId=");
      out.print(hotelDetails.get("hotelId"));
      out.write("\" class=\"btn btn-primary book-button mb-3\"> Book Now\r\n");
      out.write("						</a> <a href=\"HotelDataServlet\"\r\n");
      out.write("							class=\"btn btn-outline-secondary back-button\"> Back to\r\n");
      out.write("							Listings </a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	");
      out.write("<style>\r\n");
      out.write(".footer {\r\n");
      out.write("	padding: 20px 0;\r\n");
      out.write("	background-color: #f1f1f1;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer a {\r\n");
      out.write("	color: inherit;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer a:hover {\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hidden-button {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\" id=\"footer\">\r\n");
      out.write("	<p class=\"text-center text-secondary\">\r\n");
      out.write("		© <a href=\"admin/login\">HotelMate</a> 2024 - All rights reserved\r\n");
      out.write("	</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap JS -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
