/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-01-15 04:25:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.HttpSession;
import jakarta.servlet.http.HttpServletRequest;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/Components/Index/about.jsp", Long.valueOf(1736534738493L));
    _jspx_dependants.put("/Components/Index/features.jsp", Long.valueOf(1736536935322L));
    _jspx_dependants.put("/Components/footer.jsp", Long.valueOf(1732558031730L));
    _jspx_dependants.put("/Components/Index/contact.jsp", Long.valueOf(1736537510353L));
    _jspx_dependants.put("/Components/navbar.jsp", Long.valueOf(1736914729416L));
    _jspx_dependants.put("/Components/Index/banner.jsp", Long.valueOf(1736534897903L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
    _jspx_imports_classes.add("jakarta.servlet.http.HttpServletRequest");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("	\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>HotelMate</title>\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg\"\r\n");
      out.write("	style=\"background-color: #343a40; border-radius: 15px; padding: 10px 20px; box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2); margin: 10px; position: fixed; top: 0px; width: calc(100% - 20px); z-index: 1000;\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<!-- Logo and Brand Name -->\r\n");
      out.write("		<a class=\"navbar-brand text-light d-flex align-items-center\"\r\n");
      out.write("			href=\"index.jsp\"> <img\r\n");
      out.write("			src=\"http://localhost:8080/HotelMate/Images/HotelmateLogo.png\"\r\n");
      out.write("			alt=\"Logo\" width=\"80\" height=\"60\"\r\n");
      out.write("			class=\"d-inline-block align-text-top\"> <span\r\n");
      out.write("			class=\"nav-link text-light active\">HotelMate</span>\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<!-- Toggler button for smaller screens -->\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\"\r\n");
      out.write("			aria-expanded=\"false\" aria-label=\"Toggle navigation\"\r\n");
      out.write("			style=\"border-color: #f8f9fa;\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\" style=\"color: #f8f9fa;\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<!-- Navbar Links -->\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("			<ul class=\"navbar-nav me-auto\">\r\n");
      out.write("				<li class=\"nav-item\"><a\r\n");
      out.write("					class=\"nav-link text-light active hover-effect\" aria-current=\"page\"\r\n");
      out.write("					href=\"index.jsp\">Home</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a\r\n");
      out.write("					class=\"nav-link text-light hover-effect\" href=\"#\"\r\n");
      out.write("					onclick=\"scrollToFeatures(event)\">Features</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a\r\n");
      out.write("					class=\"nav-link text-light hover-effect\" href=\"HotelDataServlet\">Hotels</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\"><a\r\n");
      out.write("					class=\"nav-link text-light hover-effect\" href=\"#\"\r\n");
      out.write("					onclick=\"scrollToContact(event)\">Contact Us</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<!-- Login/Sign Up or Account Dropdown -->\r\n");
      out.write("			<ul class=\"navbar-nav ms-auto gap-3\">\r\n");
      out.write("				");

				// Check if the session exists and retrieve user data
				if (session.getAttribute("userEmail") != null) {
					String username = (String) session.getAttribute("userEmail"); 
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle text-light\" href=\"#\"\r\n");
      out.write("					id=\"userDropdown\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("					aria-expanded=\"false\"> <i class=\"bi bi-person-circle\"\r\n");
      out.write("						style=\"font-size: 2rem;\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("						aria-labelledby=\"userDropdown\">\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"mybookings.jsp\">My\r\n");
      out.write("								Bookings</a></li>\r\n");
      out.write("						<li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"LogoutServlet\">Logout</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				");

				} else {
				// User is not logged in
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link login-btn\"\r\n");
      out.write("					href=\"login.jsp\">Login</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link signup-btn\"\r\n");
      out.write("					href=\"signup.jsp\">Sign Up</a></li>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".hover-effect {\r\n");
      out.write("	transition: color 0.3s ease, background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hover-effect:hover {\r\n");
      out.write("	color: #97CC04 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn, .signup-btn {\r\n");
      out.write("	background-color: #97CC04;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	padding: 8px 15px;\r\n");
      out.write("	transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn:hover, .signup-btn:hover {\r\n");
      out.write("	background-color: #76b302;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Banner -->\r\n");
      out.write("	");
      out.write("<style>\r\n");
      out.write("/* Banner styling */\r\n");
      out.write(".banner {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	background-image:\r\n");
      out.write("		url(\"http://localhost:8080/HotelMate/Images/HotelMateBanner.jpeg\");\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-position: center;\r\n");
      out.write("	height: 700px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: flex-start;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Overlay for gradient effect */\r\n");
      out.write(".banner-overlay {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	background: linear-gradient(to right, rgba(0, 0, 0, 0.8),\r\n");
      out.write("		rgba(0, 0, 0, 0.3));\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Content styling within the banner */\r\n");
      out.write(".banner-content {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("	max-width: 650px;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Headline styling */\r\n");
      out.write(".banner-content h1 {\r\n");
      out.write("	font-size: 3rem;\r\n");
      out.write("	font-weight: 800;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner-content h1 span {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner-content .line1 {\r\n");
      out.write("	color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner-content .line2 {\r\n");
      out.write("	color: #15803d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Subtitle styling */\r\n");
      out.write(".banner-content p {\r\n");
      out.write("	font-size: 1.2rem;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	color: #e2e2e2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Button styling */\r\n");
      out.write(".banner-content .btn-primary, .banner-content .btn-outline-light {\r\n");
      out.write("	padding: 10px 25px;\r\n");
      out.write("	font-size: 1.1rem;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	transition: background-color 0.3s ease, color 0.3s ease, transform 0.2s\r\n");
      out.write("		ease;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner-content .btn-primary {\r\n");
      out.write("	background-color: #15803d;\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner-content .btn-primary:hover {\r\n");
      out.write("	background-color: #22c55e;\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner-content .btn-outline-light {\r\n");
      out.write("	color: #15803d;\r\n");
      out.write("	border: 2px solid #15803d;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner-content .btn-outline-light:hover {\r\n");
      out.write("	color: #166534;\r\n");
      out.write("	border: 2px solid #166534;\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"banner\">\r\n");
      out.write("	<div class=\"banner-overlay\"></div>\r\n");
      out.write("	<!-- Overlay for better text visibility -->\r\n");
      out.write("	<div class=\"banner-content text-center\">\r\n");
      out.write("		<h1>\r\n");
      out.write("			<span class=\"line1\">Stay Affordably,</span> <span class=\"line2\">Travel\r\n");
      out.write("				Comfortably</span>\r\n");
      out.write("		</h1>\r\n");
      out.write("		<p>HotelMate offers affordable, clean hotels for travelers across\r\n");
      out.write("			India, providing a comfortable stay wherever you go. Find a reliable\r\n");
      out.write("			place to rest, whether you're in a bustling city or a quiet town.</p>\r\n");
      out.write("		<div class=\"mt-4 d-flex justify-content-center\">\r\n");
      out.write("			<a href=\"signup.jsp\" class=\"btn btn-primary\">Get Started</a> <a\r\n");
      out.write("				href=\"javascript:void(0);\" class=\"btn btn-outline-light\"\r\n");
      out.write("				onclick=\"scrollToAbout()\">About Us</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function scrollToAbout() {\r\n");
      out.write("		const aboutSection = document.getElementById('about');\r\n");
      out.write("		if (aboutSection) {\r\n");
      out.write("			aboutSection.scrollIntoView({\r\n");
      out.write("				behavior : 'smooth'\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- About -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin-right: auto;\r\n");
      out.write("	margin-left: auto;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	position: relative !important;\r\n");
      out.write("	padding: 0 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-start {\r\n");
      out.write("	text-align: left !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-break {\r\n");
      out.write("	word-break: break-word;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("	border: 1px solid transparent;\r\n");
      out.write("	padding: 0.375rem 0.75rem;\r\n");
      out.write("	font-size: 1rem;\r\n");
      out.write("	line-height: 1.5;\r\n");
      out.write("	border-radius: 0.25rem;\r\n");
      out.write("	transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out,\r\n");
      out.write("		border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	background-color: #0d6efd;\r\n");
      out.write("	border-color: #0d6efd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-container {\r\n");
      out.write("	padding: 60px 0;\r\n");
      out.write("	background: url(\"http://localhost:8080/HotelMate/Images/AboutBg.jpg\")\r\n");
      out.write("		center center/cover no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".elements-grid {\r\n");
      out.write("	padding: 0px 0px 0px 10px;\r\n");
      out.write("	background: rgba(0, 0, 0, 0);\r\n");
      out.write("	border-radius: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".d-flex {\r\n");
      out.write("	display: flex !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".align-items-center {\r\n");
      out.write("	align-items: center !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".position-relative {\r\n");
      out.write("	position: relative !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mw-100 {\r\n");
      out.write("	max-width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".me-2 {\r\n");
      out.write("	margin-right: .5rem !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ms-2 {\r\n");
      out.write("	margin-left: .5rem !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".w-100 {\r\n");
      out.write("	width: 100% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mt-4 {\r\n");
      out.write("	margin-top: 1.5rem !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container-fluid {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin-right: auto;\r\n");
      out.write("	margin-left: auto;\r\n");
      out.write("	padding-right: var(--bs-gutter-x, 0.75rem);\r\n");
      out.write("	padding-left: var(--bs-gutter-x, 0.75rem);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-heading {\r\n");
      out.write("	font-size: 40px;\r\n");
      out.write("	color: rgb(25, 70, 61);\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-subheading {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: rgb(49, 53, 56);\r\n");
      out.write("	padding: 20px 0 20px 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-summary {\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: rgb(255, 255, 255);\r\n");
      out.write("	background: rgb(176, 176, 176);\r\n");
      out.write("	padding: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("	background-color: #15803d;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 6px 20px;\r\n");
      out.write("	font-size: 1.1rem;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	transition: background-color 0.3s ease, color 0.3s ease, transform 0.2s\r\n");
      out.write("		ease;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("	background-color: #22c55e;\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<section\r\n");
      out.write("	id = \"about\"\r\n");
      out.write("	class=\"block container-fluid position-relative view text-start section-container\">\r\n");
      out.write("	<div class=\"main-wrapper container p-0\">\r\n");
      out.write("		<div class=\"container-fluid p-0 position-relative\">\r\n");
      out.write("			<div class=\"h-auto moveItem-1\">\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div id=\"swiper\" class=\"elements-grid position-relative null\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-12 col-md-7 d-flex align-items-center\">\r\n");
      out.write("								<div class=\"mw-100\">\r\n");
      out.write("									<div id=\"heading\"\r\n");
      out.write("										class=\"text-break m-0 elements text text-start section-heading\">\r\n");
      out.write("										Affordable and Comfortable Stays with HotelMate</div>\r\n");
      out.write("									<div id=\"summary\"\r\n");
      out.write("										class=\"text-break elements textHtml text-start section-subheading\">\r\n");
      out.write("										HotelMate offers affordable, clean hotels across India,\r\n");
      out.write("										ensuring a comfortable stay for every traveler.</div>\r\n");
      out.write("									<div class=\"\">\r\n");
      out.write("										<a href=\"signup.jsp\" class=\"btn btn-primary\">Get Started</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-12 col-md-5\">\r\n");
      out.write("								<div class=\"position-relative w-100 ai-generated\"\r\n");
      out.write("									style=\"padding: 23px 0px 10px; background: rgba(0, 0, 0, 0);\">\r\n");
      out.write("									<img id=\"banner\" class=\"elements image w-100\"\r\n");
      out.write("										src=\"https://media.mediadirhub.com/images/image-1x1.png\"\r\n");
      out.write("										alt=\"\"\r\n");
      out.write("										style=\"background: url('http://localhost:8080/HotelMate/Images/AboutImg.jpeg') center center/cover no-repeat; border-radius: 0px;\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<div id=\"footerSummary\"\r\n");
      out.write("						class=\"text-break elements textHtml mobile-d-none text-center footer-summary\">\r\n");
      out.write("						HotelMate is a streamlined hotel booking platform designed to\r\n");
      out.write("						facilitate easy reservations at hotels within the brand. The Room\r\n");
      out.write("						Reservation feature allows users to quickly book rooms with\r\n");
      out.write("						various amenities, ensuring a seamless and user-friendly booking\r\n");
      out.write("						experience.</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Featuress -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section id=\"features\" class=\"mt-2\">\r\n");
      out.write("	<div class=\"container py-2\">\r\n");
      out.write("		<div class=\"text-center mb-5\">\r\n");
      out.write("			<h1 class=\"display-4\">\r\n");
      out.write("				Why Choose <span class=\"text-success\">HotelMate</span>?\r\n");
      out.write("			</h1>\r\n");
      out.write("			<p class=\"lead text-muted\">At HotelMate, we connect you to\r\n");
      out.write("				top-rated hotels across India, providing comfort, convenience, and\r\n");
      out.write("				easy booking for your travel.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Features Section -->\r\n");
      out.write("		<div class=\"row text-center\">\r\n");
      out.write("			<!-- Feature Item 1 -->\r\n");
      out.write("			<div class=\"col-md-4 mb-4\">\r\n");
      out.write("				<div class=\"card h-100 border-0\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<i class=\"bi bi-house-door text-success\" style=\"font-size: 2rem;\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("						<h5 class=\"card-title\">Easy Booking</h5>\r\n");
      out.write("						<p class=\"card-text\">Simplify your travel with fast, easy\r\n");
      out.write("							hotel booking. Enjoy streamlined booking with no hassle and\r\n");
      out.write("							instant confirmation.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Feature Item 2 -->\r\n");
      out.write("			<div class=\"col-md-4 mb-4\">\r\n");
      out.write("				<div class=\"card h-100 border-0\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<i class=\"bi bi-people text-success\" style=\"font-size: 2rem;\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("						<h5 class=\"card-title\">Comfort & Quality</h5>\r\n");
      out.write("						<p class=\"card-text\">Discover exceptional stays with high\r\n");
      out.write("							standards of comfort, cleanliness, and quality service tailored\r\n");
      out.write("							to your needs.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Feature Item 3 -->\r\n");
      out.write("			<div class=\"col-md-4 mb-4\">\r\n");
      out.write("				<div class=\"card h-100 border-0\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<i class=\"bi bi-shield-check text-success\"\r\n");
      out.write("								style=\"font-size: 2rem;\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("						<h5 class=\"card-title\">Trusted Ratings</h5>\r\n");
      out.write("						<p class=\"card-text\">Book confidently with our trusted rating\r\n");
      out.write("							system, designed to help you choose the best stays based on real\r\n");
      out.write("							guest reviews.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section id=\"features\"\r\n");
      out.write("	class=\"block container-fluid position-relative view text-start section-container\">\r\n");
      out.write("	<div class=\"main-wrapper container p-0\">\r\n");
      out.write("		<div class=\"container-fluid p-0 position-relative\">\r\n");
      out.write("			<div class=\"h-auto moveItem-1\">\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div id=\"swiper\" class=\"elements-grid position-relative null\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-12 col-md-5\">\r\n");
      out.write("								<div class=\"position-relative w-100\"\r\n");
      out.write("									style=\"padding: 23px 0px 10px;\">\r\n");
      out.write("									<img id=\"banner\" class=\"elements image w-100\"\r\n");
      out.write("										src=\"https://media.mediadirhub.com/images/image-1x1.png\"\r\n");
      out.write("										alt=\"\"\r\n");
      out.write("										style=\"background: url('http://localhost:8080/HotelMate/Images/featureImg.jpeg') center center/cover no-repeat;\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-12 col-md-7 d-flex align-items-center\">\r\n");
      out.write("								<div class=\"mw-100\">\r\n");
      out.write("									<div id=\"heading\" class=\"text-break m-0 section-heading\">\r\n");
      out.write("										Easy Hotel Reservations</div>\r\n");
      out.write("									<div id=\"summary\" class=\"text-break section-subheading\">\r\n");
      out.write("										Seamless and user-friendly booking experience for various\r\n");
      out.write("										amenities.</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Contact -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<section id=\"contact\" class=\"py-3\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"text-center mb-5\">\r\n");
      out.write("			<p class=\"text-success font-weight-medium\">Contact us</p>\r\n");
      out.write("			<h1 class=\"display-4 font-weight-bold text-dark\">Get in touch</h1>\r\n");
      out.write("			<p class=\"text-muted\">Our friendly team is always here to chat.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<!-- Email Card -->\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("				<div class=\"d-flex flex-column align-items-center text-center\">\r\n");
      out.write("					<div class=\"bg-light text-success rounded-circle p-3 mb-3\">\r\n");
      out.write("						<i class=\"bi bi-envelope-fill\" style=\"font-size: 2rem;\"></i>\r\n");
      out.write("						<!-- Bootstrap Email Icon -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<h5 class=\"font-weight-bold text-dark\">Email</h5>\r\n");
      out.write("					<p class=\"text-muted\">Our friendly team is here to help.</p>\r\n");
      out.write("					<p class=\"text-success\">customer_care@hotelmate.com</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Office Card -->\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("				<div class=\"d-flex flex-column align-items-center text-center\">\r\n");
      out.write("					<div class=\"bg-light text-success rounded-circle p-3 mb-3\">\r\n");
      out.write("						<i class=\"bi bi-geo-alt-fill\" style=\"font-size: 2rem;\"></i>\r\n");
      out.write("						<!-- Bootstrap Location Icon -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<h5 class=\"font-weight-bold text-dark\">Office</h5>\r\n");
      out.write("					<p class=\"text-muted\">Come say hello at our office HQ.</p>\r\n");
      out.write("					<p class=\"text-success\">EM-4/1 Sector V Bidhannagar KOL 700091\r\n");
      out.write("						IND</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Helpline Card -->\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("				<div class=\"d-flex flex-column align-items-center text-center\">\r\n");
      out.write("					<div class=\"bg-light text-success rounded-circle p-3 mb-3\">\r\n");
      out.write("						<i class=\"bi bi-telephone-fill\" style=\"font-size: 2rem;\"></i>\r\n");
      out.write("						<!-- Bootstrap Phone Icon -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<h5 class=\"font-weight-bold text-dark\">Helpline</h5>\r\n");
      out.write("					<p class=\"text-muted\">Available 24/7</p>\r\n");
      out.write("					<p class=\"text-success\">+1 (555) 000-0000</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	");
      out.write("<style>\r\n");
      out.write(".footer {\r\n");
      out.write("	padding: 20px 0;\r\n");
      out.write("	background-color: #f1f1f1;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class='footer' id=\"footer\">\r\n");
      out.write("	<p class=\"text-center text-secondary\">© HotelMate 2024 - All\r\n");
      out.write("		rights reserved</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap JS  -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		window.onload = function() {\r\n");
      out.write("			if (localStorage.getItem('scrollToContact') === 'true') {\r\n");
      out.write("				var aboutElement = document.getElementById(\"contact\");\r\n");
      out.write("				if (aboutElement) {\r\n");
      out.write("					window.scrollTo({\r\n");
      out.write("						top : aboutElement.offsetTop - 100,\r\n");
      out.write("						behavior : 'smooth'\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("				localStorage.removeItem('scrollToContact');\r\n");
      out.write("			}\r\n");
      out.write("			if (localStorage.getItem('scrollToFeatures') === 'true') {\r\n");
      out.write("				var featuresElement = document.getElementById(\"features\");\r\n");
      out.write("				if (featuresElement) {\r\n");
      out.write("					window.scrollTo({\r\n");
      out.write("						top : featuresElement.offsetTop - 100,\r\n");
      out.write("						behavior : 'smooth'\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("				localStorage.removeItem('scrollToFeatures');\r\n");
      out.write("			}\r\n");
      out.write("		};\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
