/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-01-10 18:36:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Components/footer.jsp", Long.valueOf(1732558031730L));
    _jspx_dependants.put("/Components/navbar.jsp", Long.valueOf(1735362339033L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Sign Up - HotelMate</title>\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup-container {\r\n");
      out.write("	max-width: 400px;\r\n");
      out.write("	margin: 150px auto;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup-btn {\r\n");
      out.write("	background-color: #97CC04;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup-btn:hover {\r\n");
      out.write("	background-color: #76b302;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("	");
      out.write("<nav class=\"navbar navbar-expand-lg\"\r\n");
      out.write("	style=\"background-color: #343a40; border-radius: 15px; padding: 10px 20px; box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2); margin: 10px; position: fixed; top: 0px; width: calc(100% - 20px); z-index: 1000;\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<!-- Logo and Brand Name -->\r\n");
      out.write("		<a class=\"navbar-brand text-light d-flex align-items-center\"\r\n");
      out.write("			href=\"index.jsp\"> <img\r\n");
      out.write("			src=\"https://res.cloudinary.com/dtgiodduq/image/upload/v1729880406/HotelMate/qthjuahg2sm9c2nlrkpp.png\"\r\n");
      out.write("			alt=\"Logo\" width=\"80\" height=\"60\"\r\n");
      out.write("			class=\"d-inline-block align-text-top\"> <span\r\n");
      out.write("			class=\"nav-link text-light active\">HotelMate</span>\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<!-- Toggler button for smaller screens -->\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\"\r\n");
      out.write("			aria-expanded=\"false\" aria-label=\"Toggle navigation\"\r\n");
      out.write("			style=\"border-color: #f8f9fa;\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\" style=\"color: #f8f9fa;\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<!-- Navbar Links -->\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("			<ul class=\"navbar-nav me-auto\">\r\n");
      out.write("				<li class=\"nav-item\"><a\r\n");
      out.write("					class=\"nav-link text-light active hover-effect\" aria-current=\"page\"\r\n");
      out.write("					href=\"index.jsp\">Home</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a\r\n");
      out.write("					class=\"nav-link text-light hover-effect\" href=\"#\">Features</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a\r\n");
      out.write("					class=\"nav-link text-light hover-effect\" href=\"HotelDataServlet\">Hotels</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<!-- Login and Sign Up links on the right -->\r\n");
      out.write("			<ul class=\"navbar-nav ms-auto gap-3\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link login-btn\"\r\n");
      out.write("					href=\"login.jsp\">Login</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link signup-btn\"\r\n");
      out.write("					href=\"signup.jsp\">Sign Up</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* Hover effect for navbar links */\r\n");
      out.write(".hover-effect {\r\n");
      out.write("	transition: color 0.3s ease, background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hover-effect:hover {\r\n");
      out.write("	color: #97CC04 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Styles for Login and Sign Up buttons */\r\n");
      out.write(".login-btn, .signup-btn {\r\n");
      out.write("	background-color: #97CC04; /* Green background */\r\n");
      out.write("	color: #fff; /* White text */\r\n");
      out.write("	border-radius: 5px; /* Rounded corners */\r\n");
      out.write("	padding: 8px 15px; /* Padding for button effect */\r\n");
      out.write("	transition: background-color 0.3s ease; /* Smooth transition */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn:hover, .signup-btn:hover {\r\n");
      out.write("	background-color: #76b302; /* Darker green on hover */\r\n");
      out.write("	color: #fff; /* Keep white text */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"signup-container\">\r\n");
      out.write("		<h2 class=\"text-center mb-4\">Sign Up</h2>\r\n");
      out.write("\r\n");
      out.write("		<!-- Display Error Alert -->\r\n");
      out.write("		");

		String error = (String) request.getAttribute("error");
		if (error != null && !error.isEmpty()) {
		
      out.write("\r\n");
      out.write("		<div class=\"alert alert-danger alert-dismissible fade show\"\r\n");
      out.write("			role=\"alert\">\r\n");
      out.write("			");
      out.print(error);
      out.write("\r\n");
      out.write("			<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"\r\n");
      out.write("				aria-label=\"Close\"></button>\r\n");
      out.write("		</div>\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<form action=\"SignupServlet\" method=\"post\">\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"name\" class=\"form-label\">Full Name</label> <input\r\n");
      out.write("					type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"email\" class=\"form-label\">Email address</label> <input\r\n");
      out.write("					type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"password\" class=\"form-label\">Password</label> <input\r\n");
      out.write("					type=\"password\" class=\"form-control\" id=\"password\" name=\"password\"\r\n");
      out.write("					required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"confirmPassword\" class=\"form-label\">Confirm\r\n");
      out.write("					Password</label> <input type=\"password\" class=\"form-control\"\r\n");
      out.write("					id=\"confirmPassword\" name=\"confirmPassword\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<button type=\"submit\" class=\"btn signup-btn w-100\">Sign Up</button>\r\n");
      out.write("			<div class=\"mt-3 text-center\">\r\n");
      out.write("				<a href=\"login.jsp\">Already have an account? Login</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	");
      out.write("<style>\r\n");
      out.write(".footer {\r\n");
      out.write("	padding: 20px 0;\r\n");
      out.write("	background-color: #f1f1f1;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class='footer' id=\"footer\">\r\n");
      out.write("	<p class=\"text-center text-secondary\">© HotelMate 2024 - All\r\n");
      out.write("		rights reserved</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap JS (Popper.js included) -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
